### PR TITLE
Prevents crash of Journal Server, if socket experiences ‘ECONNRESET’

### LINKED ISSUE #40: Journal Server exits due to "Unhandled 'error' event" (ECONNRESET exception in underlying socket)
1. Was this issue on the **Journal Server** or a **Client** connected to the Journal
Server?

Journal Server

2. Does the Journal Server have a **custom config**?

Just to disable the subscription requirement... not relevant.

3. Can you **recreate the issue** or was it a **one-time occurrence**?

Happens a lot.

I'm running EDJS journal server in a CMD prompt on Windows 10. I connect to it from Chrome, running some app I'm working on, using the standard JS websocket client to connect to the server. This second machine is running OSX 10.14.3.

Refreshing the browser window will cause the client to  reconnect and "reset" the prior connection. There's a good chance (1 in 10) that the server on the Windows side will exit:

```cmd
Client 58477d50-4175-11e9-b0e9-dffd08e6ae7c connected via Web Socket.
Total clients: 1
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at WebSocket.finalize (xxx\node_modules\ws\lib\WebSocket.js:182:41)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

4. What **version** of the *Elite Dangerous Journal Server* are you running?

```json
{
  "journalServer": "xxx",
  "journal": "Journal.xxx.log",
  "commander": "xxx",
  "serverVersion": "3.0.0",
  "clientID": "58477d50-4175-11e9-b0e9-dffd08e6ae7c",
  "clientName": null,
  "payload": {
    "timestamp": "xxx",
    "event": "Fileheader",
    "part": 1,
    "language": "English\\UK",
    "gameversion": "3.3.5.802 EDH",
    "build": "r193824/r0 "
  }
}
```

### PR DESCRIPTION
**Pull request by rolandbosa**
Fixes #40 

**Proposed Changes**:
Add handler for 'error' event to socket.

---

@DVDAGames/ed-journal-server-maintainers

### CODE REVIEW

**Comment by ericrallen** [comment]
@rolandbosa Thanks for the PR!

I'll get this merged in and try to publish out a new version later today.

File: src/index.js [hunk 1]
```diff
@@ -287,6 +287,16 @@ class EliteDangerousJournalServer {
       socket.isReceiving = true;
     });
 
+    // handle socket errors
+    socket.on('error', (err) => {
+      // ignore that pesky ECONNRESET, socket will disconnect anyway, rethrow others
+      if (err.code && (err.code === 'ECONNRESET')) {
+        console.log(`${chalk.cyan('Socket')} ${chalk.red('Ignoring ECONNRESET')}`);
```
Comment (ericrallen) [inline src/index.js]: I wonder if this should be a `console.error` or `console.warn` instead of `console.log` given that it is encountering an error, but we're just sort of ignoring it.

Any thoughts, @rolandbosa?

**Review by ericrallen — APPROVED** [review]
Approved, just one question about what method we should use.

File: src/index.js (hunk 1 above)
Comment (rolandbosa) [reply src/index.js]: I'd prefer it to be completely muted, to be honest. There's no real information to be gained from this message. If you agree, I'll update the PR accordingly.

Comment (ericrallen) [reply src/index.js]: Yeah, I could get behind something like:

```js
if (err.code !== 'ECONNRESET') {
  throw err;
}
```

Comment (ericrallen) [reply src/index.js]: I went ahead and made the change and added it to the CHANGELOG so that I can get it published out before the weekend ends.

Thanks again for the PR! I look forward to seeing what you build with it.
