### PR TITLE
Wrap parsing of files in exception handler

### LINKED ISSUE #48: Server crashes when parsing 'status.json'
1. Was this issue on the **Journal Server** or a **Client** connected to the Journal
Server?

Journal Server crashes.

2. Does the Journal Server have a **custom config**?

It does, but not relevant to the problem at hand.

3. Can you **recreate the issue** or was it a **one-time occurrence**?

It happens fairly often. The file 'status.json' is written by ED quite often. If the file notification hits, the file on disk may still be only partially written. Parsing that will cause an exception, which isn't handled and crashes the server.

4. What **version** of the *Elite Dangerous Journal Server* are you running?

3.1.0

### PR DESCRIPTION
**Pull request by rolandbosa**
Sometimes, the file is not fully written to disk, and the JSON is therefore invalid. This MR catches that case and ignores that particular file update. Happens fairly often with `status.json`. A subsequent update to the file might read it at a better point in time and the parsing will succeed.

Fixes #48 

**Proposed Changes**:

Wrap the JSON parsing in exception handler, ignore the "SyntaxError" exception caused by malformed/incomplete JSON.

The log message highlights when the exception occurs. It should get removed/squelched it before final merge.

---

@DVDAGames/ed-journal-server-maintainers

### CODE REVIEW

**Comment by ericrallen** [comment]
Sorry for the delay, I'll try to take a look at this shortly.

Thanks for the contribution.

File: src/index.js [hunk 1]
```diff
@@ -574,9 +574,20 @@ class EliteDangerousJournalServer {
...
+        }
+      }
+      catch (err) {
+        /* If the file is in the middle of being flushed to disk, we can
+         * get 'SyntaxError: Unexpected end of JSON input' in JSON.parse().
+         */
+        if (err.name != 'SyntaxError') {
+          throw err;
+        }
+        console.log(`${chalk.red('Ignoring error:')} ${chalk.magenta(err)}`);
```
Comment (ericrallen) [inline src/index.js:590]: It's totally out of scope for this PR, but do you think it would be useful to have a `DEBUG` environment variable that would let you enable/disable this kind of logging for development/testing purposes?

Comment (ericrallen) [reply src/index.js:590]: I have a few other questions I'd love to get your opinion on. They are outside the scope of this PR, but I'd really appreciate your thoughts on them.

1) I know the Journal's JSON Lines implementation is a little different than how the `status.json` file is handled, but do you think we should add a similar guard around the reading of the Journal? I never encountered this kind of error with it while testing and playing, but that could have just been blind luck.

2) Is the current read interval quick enough to pick up the changes without a noticeable delay when this error is encountered or should we consider adding a short retry interval when this happens? You are far more familiar with it, so if you're happy with the current performance then I think we're probably good.

**Review by ericrallen — APPROVED** [review]
👍 

I'll try to publish out the new version this evening.

**Comment by ericrallen** [comment]
@rolandbosa This has been released in version `3.2.0`.

Thanks again for the contributions!

File: src/index.js (hunk 1 above)
Comment (rolandbosa) [reply src/index.js:590]: Hey Eric

Sorry for the delay on my side, I got a bit swamped with other stuff. Let me gather my thoughts on your questions and I'll get back to you soon.
